import os
import json
from typing import Dict, Any
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

async def send_risk_alert(user_email: str, company_name: str, risk_analysis: Dict[str, Any]) -> bool:
    """
    Send email alert for high-risk startups using SendGrid
    """
    try:
        # Get SendGrid API key from environment
        sendgrid_api_key = os.getenv("SENDGRID_API_KEY")

        if not sendgrid_api_key:
            print("SendGrid API key not configured")
            return False

        # Prepare email content
        subject = f"🚨 High Risk Alert: {company_name}"

        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #d32f2f;">⚠️ High Risk Startup Detected</h2>

            <div style="background-color: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <h3>{company_name}</h3>
                <p><strong>Overall Risk Score:</strong> {risk_analysis['overall_score']}%</p>
                <p><strong>Risk Category:</strong> {risk_analysis['risk_category']}</p>
            </div>

            <h4>Risk Breakdown:</h4>
            <ul>
                <li><strong>Fraud Risk:</strong> {risk_analysis['fraud_risk']}%</li>
                <li><strong>Compliance Risk:</strong> {risk_analysis['compliance_risk']}%</li>
                <li><strong>Traction Risk:</strong> {risk_analysis['traction_risk']}%</li>
                <li><strong>Founder Risk:</strong> {risk_analysis['founder_risk']}%</li>
            </ul>

            <h4>🚩 Red Flags Detected:</h4>
            <ul>
                {"".join([f"<li>{flag}</li>" for flag in risk_analysis['red_flags']])}
            </ul>

            <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <p><strong>Recommendation:</strong> Exercise extreme caution before investing. 
                Conduct thorough due diligence and consider seeking additional expert advice.</p>
            </div>

            <p style="color: #666; font-size: 12px;">
                This alert was generated by FinXray AI Risk Analysis Platform.<br>
                For questions, contact support@finxray.com
            </p>
        </div>
        """

        # Create and send email
        message = Mail(
            from_email='alerts@finxray.com',
            to_emails=user_email,
            subject=subject,
            html_content=html_content
        )

        sg = SendGridAPIClient(api_key=sendgrid_api_key)
        response = sg.send(message)

        if response.status_code == 202:
            print(f"Risk alert email sent successfully to {user_email}")
            return True
        else:
            print(f"Failed to send email. Status code: {response.status_code}")
            return False

    except Exception as e:
        print(f"Email sending error: {str(e)}")
        return False

def send_subscription_confirmation(user_email: str, plan_details: Dict[str, Any]) -> bool:
    """
    Send subscription confirmation email
    """
    try:
        sendgrid_api_key = os.getenv("SENDGRID_API_KEY")

        if not sendgrid_api_key:
            return False

        subject = "✅ FinXray Subscription Activated"

        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #4caf50;">Welcome to FinXray Premium!</h2>

            <p>Your subscription has been successfully activated.</p>

            <div style="background-color: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <h3>Subscription Details:</h3>
                <p><strong>Plan:</strong> {plan_details.get('plan', 'Premium')}</p>
                <p><strong>Amount:</strong> ₹{plan_details.get('amount', '25,000')}/month</p>
                <p><strong>Status:</strong> Active</p>
            </div>

            <h4>Premium Features Unlocked:</h4>
            <ul>
                <li>Unlimited startup analyses</li>
                <li>Advanced AI risk models</li>
                <li>Real-time email alerts</li>
                <li>Priority customer support</li>
                <li>Custom risk thresholds</li>
            </ul>

            <p>Start analyzing startups now at <a href="https://finxray.vercel.app">finxray.vercel.app</a></p>

            <p style="color: #666; font-size: 12px;">
                Questions? Contact us at support@finxray.com
            </p>
        </div>
        """

        message = Mail(
            from_email='billing@finxray.com',
            to_emails=user_email,
            subject=subject,
            html_content=html_content
        )

        sg = SendGridAPIClient(api_key=sendgrid_api_key)
        response = sg.send(message)

        return response.status_code == 202

    except Exception as e:
        print(f"Subscription email error: {str(e)}")
        return False
